version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"

    ports:
        - "1450:1433"

    restart: always

    environment:
        MSSQL_SA_PASSWORD: "S3cur3P@ssW0rd!"
        ACCEPT_EULA: "Y"

  gotw:
    build:
      context: .
      dockerfile: GoTWAPI/Dockerfile
    ports:
        - "8080:80"
    depends_on:
        - db

    restart: always
    environment:
        - DBHOST=db
        - DBPORT=1450
        - DBUSER=sa
        - DBPASSWORD=S3cur3P@ssW0rd!
        - DBNAME=GoTW
        - ASPNETCORE_ENVIRONMENT=Development
        