// <auto-generated />
using System;
using GotwAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoTWAPI.Migrations
{
    [DbContext(typeof(CommanderContext))]
    partial class CommanderContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GotwAPI.Context.CommanderSkill", b =>
                {
                    b.Property<int>("CommanderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommanderId"), 1L, 1);

                    b.Property<string>("Awakening")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AwakeningId")
                        .HasColumnType("int");

                    b.Property<string>("ClassType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Expedition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExpeditionId")
                        .HasColumnType("int");

                    b.Property<string>("Fighting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FigthingId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skills")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrategicSkill")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StrategicSkillId")
                        .HasColumnType("int");

                    b.Property<string>("TrainingGround")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrainingGroundId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weirwood")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WeirwoodId")
                        .HasColumnType("int");

                    b.HasKey("CommanderId");

                    b.ToTable("CommanderSkill");
                });
#pragma warning restore 612, 618
        }
    }
}
